CREATE TABLE `DEMO`.`TEST_CONTENT` 
(
  TEST_SEQ_NO NUMBER(19,0) NOT NULL 
, NAME VARCHAR(100) NOT NULL  
, CONSTRAINT PK_TEST_CONTENT PRIMARY KEY 
  (
    TEST_SEQ_NO 
  )
);


ALTER TABLE DEMO.TEST_CONTENT COMMENT '테스트';