server:
    port: 8082
spring:
    jpa:
        show-sql: false
        generate-ddl: false
        # database-platform: org.hibernate.dialect.Oracle10gDialect
        hibernate:
            # ddl-auto: create  # create or update
            use-new-id-generator-mappings: false
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    thymeleaf:
        prefix: "classpath:/static/"
    